In [315]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

<h3> Bike lines </h3>

In [316]:
df=pd.read_csv(r'C:\Users\majal\Downloads\archive (5)\comptagesvelo2015.csv')
df.head()

,Date,Unnamed: 1,Berri1,Boyer,Brébeuf,CSC (Côte Sainte-Catherine),Maisonneuve_1,Maisonneuve_2,Maisonneuve_3,Notre-Dame,...,Pont_Jacques_Cartier,Rachel / Hôtel de Ville,Rachel / Papineau,René-Lévesque,Saint-Antoine,Saint-Laurent U-Zelt Test,Saint-Urbain,Totem_Laurier,University,Viger
0,01/01/2015,00:00,58,12,4,17,33.0,49,21,16,...,NaN,58,91,24,3,NaN,17,78,21,6
1,02/01/2015,00:00,75,7,5,15,30.0,113,27,9,...,NaN,109,177,32,13,NaN,11,57,77,4
2,03/01/2015,00:00,79,7,3,7,30.0,107,36,12,...,NaN,71,131,33,5,NaN,14,174,40,5
3,04/01/2015,00:00,10,1,21,0,10.0,35,29,1,...,NaN,6,11,6,1,NaN,1,20,6,0
4,05/01/2015,00:00,42,0,2,0,27.0,90,21,1,...,NaN,0,5,49,20,NaN,0,41,56,10

In [317]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         319 non-null    object
 1   Unnamed: 1                   319 non-null    object
 2   Berri1                       319 non-null    int64
 3   Boyer                        319 non-null    int64
 4   Brébeuf                      319 non-null    int64
 5   CSC (Côte Sainte-Catherine)  319 non-null    int64
 6   Maisonneuve_1                62 non-null     float64
 7   Maisonneuve_2                319 non-null    int64
 8   Maisonneuve_3                319 non-null    int64
 9   Notre-Dame                   319 non-null    int64
 10  Parc                         319 non-null    int64
 11  Parc U-Zelt Test             52 non-null     float64
 12  PierDup                      319 non-null    int64
 13  Pont_Jacques_Cartier         209 non-null    float64
 14  Rachel / Hôtel de Ville      319 non-null    int64
 15  Rachel / Papineau            319 non-null    int64
 16  René-Lévesque                319 non-null    int64
 17  Saint-Antoine                319 non-null    int64
 18  Saint-Laurent U-Zelt Test    50 non-null     float64
 19  Saint-Urbain                 319 non-null    int64
 20  Totem_Laurier                319 non-null    int64
 21  University                   319 non-null    int64
 22  Viger                        319 non-null    int64
dtypes: float64(4), int64(17), object(2)
memory usage: 57.4+ KB

In [318]:
df.shape

(319, 23)

In [319]:
df.isnull().sum()

Date                             0
Unnamed: 1                       0
Berri1                           0
Boyer                            0
Brébeuf                          0
CSC (Côte Sainte-Catherine)      0
Maisonneuve_1                  257
Maisonneuve_2                    0
Maisonneuve_3                    0
Notre-Dame                       0
Parc                             0
Parc U-Zelt Test               267
PierDup                          0
Pont_Jacques_Cartier           110
Rachel / Hôtel de Ville          0
Rachel / Papineau                0
René-Lévesque                    0
Saint-Antoine                    0
Saint-Laurent U-Zelt Test      269
Saint-Urbain                     0
Totem_Laurier                    0
University                       0
Viger                            0
dtype: int64

In [320]:
columns = [col for col in df.columns if (df[col].isnull().sum() / df.shape[0]) <= 0.05]
print(columns)

['Date', 'Unnamed: 1', 'Berri1', 'Boyer', 'Brébeuf', 'CSC (Côte Sainte-Catherine)', 'Maisonneuve_2', 'Maisonneuve_3', 'Notre-Dame', 'Parc', 'PierDup', 'Rachel / Hôtel de Ville', 'Rachel / Papineau', 'René-Lévesque', 'Saint-Antoine', 'Saint-Urbain', 'Totem_Laurier', 'University', 'Viger']

In [321]:
df=df[columns]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         319 non-null    object
 1   Unnamed: 1                   319 non-null    object
 2   Berri1                       319 non-null    int64
 3   Boyer                        319 non-null    int64
 4   Brébeuf                      319 non-null    int64
 5   CSC (Côte Sainte-Catherine)  319 non-null    int64
 6   Maisonneuve_2                319 non-null    int64
 7   Maisonneuve_3                319 non-null    int64
 8   Notre-Dame                   319 non-null    int64
 9   Parc                         319 non-null    int64
 10  PierDup                      319 non-null    int64
 11  Rachel / Hôtel de Ville      319 non-null    int64
 12  Rachel / Papineau            319 non-null    int64
 13  René-Lévesque                319 non-null    int64
 14  Saint-Antoine                319 non-null    int64
 15  Saint-Urbain                 319 non-null    int64
 16  Totem_Laurier                319 non-null    int64
 17  University                   319 non-null    int64
 18  Viger                        319 non-null    int64
dtypes: int64(17), object(2)
memory usage: 47.5+ KB

In [322]:
df.shape

(319, 19)

In [323]:
# sns.pairplot(df)
# plt.show()

In [324]:
df.select_dtypes("object").head()

         Date Unnamed: 1
0  01/01/2015      00:00
1  02/01/2015      00:00
2  03/01/2015      00:00
3  04/01/2015      00:00
4  05/01/2015      00:00

In [325]:
df.shape

(319, 19)

In [326]:
df.isnull().sum()

Date                           0
Unnamed: 1                     0
Berri1                         0
Boyer                          0
Brébeuf                        0
CSC (Côte Sainte-Catherine)    0
Maisonneuve_2                  0
Maisonneuve_3                  0
Notre-Dame                     0
Parc                           0
PierDup                        0
Rachel / Hôtel de Ville        0
Rachel / Papineau              0
René-Lévesque                  0
Saint-Antoine                  0
Saint-Urbain                   0
Totem_Laurier                  0
University                     0
Viger                          0
dtype: int64

In [327]:
df.head()

,Date,Unnamed: 1,Berri1,Boyer,Brébeuf,CSC (Côte Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Rachel / Hôtel de Ville,Rachel / Papineau,René-Lévesque,Saint-Antoine,Saint-Urbain,Totem_Laurier,University,Viger
0,01/01/2015,00:00,58,12,4,17,49,21,16,16,7,58,91,24,3,17,78,21,6
1,02/01/2015,00:00,75,7,5,15,113,27,9,32,11,109,177,32,13,11,57,77,4
2,03/01/2015,00:00,79,7,3,7,107,36,12,18,2,71,131,33,5,14,174,40,5
3,04/01/2015,00:00,10,1,21,0,35,29,1,0,0,6,11,6,1,1,20,6,0
4,05/01/2015,00:00,42,0,2,0,90,21,1,1,6,0,5,49,20,0,41,56,10

In [328]:
# df=df.set_index('Date')
# df.head()

<h3> Weather </h3>

In [329]:
weather_df = pd.read_csv(r"C:\Users\majal\Downloads\archive (6)\eng-daily-01012015-12312015.csv")
weather_df.head()

,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,2015-01-01,2015,1,1,‡,-3.0,NaN,-7.6,NaN,-5.3,...,1.8,NaN,1.8,NaN,0.0,NaN,22.0,NaN,63,NaN
1,2015-01-02,2015,1,2,‡,-3.4,NaN,-14.2,NaN,-8.8,...,0.0,T,0.0,T,1.0,NaN,27.0,NaN,50,NaN
2,2015-01-03,2015,1,3,‡,-8.5,NaN,-17.7,NaN,-13.1,...,17.0,NaN,17.0,NaN,1.0,NaN,3.0,NaN,41,NaN
3,2015-01-04,2015,1,4,‡,3.0,NaN,-8.6,NaN,-2.8,...,0.4,NaN,27.2,NaN,8.0,NaN,26.0,NaN,69,NaN
4,2015-01-05,2015,1,5,‡,-5.3,NaN,-17.9,NaN,-11.6,...,0.0,T,0.0,T,6.0,NaN,27.0,NaN,74,NaN

In [330]:
# weather_df = weather_df.rename(columns={'Date/Time':'Date'})
# weather_df = weather_df.set_index('Date')

In [331]:
weather_df.head()

,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,2015-01-01,2015,1,1,‡,-3.0,NaN,-7.6,NaN,-5.3,...,1.8,NaN,1.8,NaN,0.0,NaN,22.0,NaN,63,NaN
1,2015-01-02,2015,1,2,‡,-3.4,NaN,-14.2,NaN,-8.8,...,0.0,T,0.0,T,1.0,NaN,27.0,NaN,50,NaN
2,2015-01-03,2015,1,3,‡,-8.5,NaN,-17.7,NaN,-13.1,...,17.0,NaN,17.0,NaN,1.0,NaN,3.0,NaN,41,NaN
3,2015-01-04,2015,1,4,‡,3.0,NaN,-8.6,NaN,-2.8,...,0.4,NaN,27.2,NaN,8.0,NaN,26.0,NaN,69,NaN
4,2015-01-05,2015,1,5,‡,-5.3,NaN,-17.9,NaN,-11.6,...,0.0,T,0.0,T,6.0,NaN,27.0,NaN,74,NaN

In [332]:
columns = [col for col in weather_df.columns if (weather_df[col].isnull().sum() / weather_df.shape[0]) <= 0.05]

columns.remove("Year")
columns.remove("Month")
columns.remove("Day")
columns.remove("Data Quality")
print(columns)

['Date/Time', 'Max Temp (°C)', 'Min Temp (°C)', 'Mean Temp (°C)', 'Heat Deg Days (°C)', 'Cool Deg Days (°C)', 'Total Rain (mm)', 'Total Snow (cm)', 'Total Precip (mm)', 'Spd of Max Gust (km/h)']

In [333]:
weather_df=weather_df[columns]
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date/Time               365 non-null    object
 1   Max Temp (°C)           365 non-null    float64
 2   Min Temp (°C)           365 non-null    float64
 3   Mean Temp (°C)          365 non-null    float64
 4   Heat Deg Days (°C)      365 non-null    float64
 5   Cool Deg Days (°C)      365 non-null    float64
 6   Total Rain (mm)         352 non-null    float64
 7   Total Snow (cm)         361 non-null    float64
 8   Total Precip (mm)       355 non-null    float64
 9   Spd of Max Gust (km/h)  364 non-null    object
dtypes: float64(8), object(2)
memory usage: 28.6+ KB

In [334]:
weather_df.head()

,Date/Time,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Snow (cm),Total Precip (mm),Spd of Max Gust (km/h)
0,2015-01-01,-3.0,-7.6,-5.3,23.3,0.0,0.0,1.8,1.8,63
1,2015-01-02,-3.4,-14.2,-8.8,26.8,0.0,0.0,0.0,0.0,50
2,2015-01-03,-8.5,-17.7,-13.1,31.1,0.0,0.0,17.0,17.0,41
3,2015-01-04,3.0,-8.6,-2.8,20.8,0.0,26.8,0.4,27.2,69
4,2015-01-05,-5.3,-17.9,-11.6,29.6,0.0,0.0,0.0,0.0,74

In [335]:
weather_df.select_dtypes("object").head()

    Date/Time Spd of Max Gust (km/h)
0  2015-01-01                     63
1  2015-01-02                     50
2  2015-01-03                     41
3  2015-01-04                     69
4  2015-01-05                     74

In [336]:
weather_df.drop(["Spd of Max Gust (km/h)"], axis=1, inplace=True)

In [337]:
weather_df.head()

,Date/Time,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Snow (cm),Total Precip (mm)
0,2015-01-01,-3.0,-7.6,-5.3,23.3,0.0,0.0,1.8,1.8
1,2015-01-02,-3.4,-14.2,-8.8,26.8,0.0,0.0,0.0,0.0
2,2015-01-03,-8.5,-17.7,-13.1,31.1,0.0,0.0,17.0,17.0
3,2015-01-04,3.0,-8.6,-2.8,20.8,0.0,26.8,0.4,27.2
4,2015-01-05,-5.3,-17.9,-11.6,29.6,0.0,0.0,0.0,0.0

<h3> Merge </h3>

In [338]:
df_merged = pd.merge(df, weather_df, left_index=True, right_index=True, how='inner')

df_merged.head()

,Date,Unnamed: 1,Berri1,Boyer,Brébeuf,CSC (Côte Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,...,Viger,Date/Time,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Snow (cm),Total Precip (mm)
0,01/01/2015,00:00,58,12,4,17,49,21,16,16,...,6,2015-01-01,-3.0,-7.6,-5.3,23.3,0.0,0.0,1.8,1.8
1,02/01/2015,00:00,75,7,5,15,113,27,9,32,...,4,2015-01-02,-3.4,-14.2,-8.8,26.8,0.0,0.0,0.0,0.0
2,03/01/2015,00:00,79,7,3,7,107,36,12,18,...,5,2015-01-03,-8.5,-17.7,-13.1,31.1,0.0,0.0,17.0,17.0
3,04/01/2015,00:00,10,1,21,0,35,29,1,0,...,0,2015-01-04,3.0,-8.6,-2.8,20.8,0.0,26.8,0.4,27.2
4,05/01/2015,00:00,42,0,2,0,90,21,1,1,...,10,2015-01-05,-5.3,-17.9,-11.6,29.6,0.0,0.0,0.0,0.0

In [339]:
df_merged.drop(['Date', 'Date/Time', 'Unnamed: 1'], axis=1, inplace=True)

In [340]:
df_merged.head()

,Berri1,Boyer,Brébeuf,CSC (Côte Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Rachel / Hôtel de Ville,...,University,Viger,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Snow (cm),Total Precip (mm)
0,58,12,4,17,49,21,16,16,7,58,...,21,6,-3.0,-7.6,-5.3,23.3,0.0,0.0,1.8,1.8
1,75,7,5,15,113,27,9,32,11,109,...,77,4,-3.4,-14.2,-8.8,26.8,0.0,0.0,0.0,0.0
2,79,7,3,7,107,36,12,18,2,71,...,40,5,-8.5,-17.7,-13.1,31.1,0.0,0.0,17.0,17.0
3,10,1,21,0,35,29,1,0,0,6,...,6,0,3.0,-8.6,-2.8,20.8,0.0,26.8,0.4,27.2
4,42,0,2,0,90,21,1,1,6,0,...,56,10,-5.3,-17.9,-11.6,29.6,0.0,0.0,0.0,0.0

In [341]:
df_merged.shape

(319, 25)

In [342]:
df_merged.isnull().sum()

Berri1                          0
Boyer                           0
Brébeuf                         0
CSC (Côte Sainte-Catherine)     0
Maisonneuve_2                   0
Maisonneuve_3                   0
Notre-Dame                      0
Parc                            0
PierDup                         0
Rachel / Hôtel de Ville         0
Rachel / Papineau               0
René-Lévesque                   0
Saint-Antoine                   0
Saint-Urbain                    0
Totem_Laurier                   0
University                      0
Viger                           0
Max Temp (°C)                   0
Min Temp (°C)                   0
Mean Temp (°C)                  0
Heat Deg Days (°C)              0
Cool Deg Days (°C)              0
Total Rain (mm)                11
Total Snow (cm)                 3
Total Precip (mm)               8
dtype: int64

In [343]:
df_merged = df_merged.dropna()
df_merged.isnull().sum()

Berri1                         0
Boyer                          0
Brébeuf                        0
CSC (Côte Sainte-Catherine)    0
Maisonneuve_2                  0
Maisonneuve_3                  0
Notre-Dame                     0
Parc                           0
PierDup                        0
Rachel / Hôtel de Ville        0
Rachel / Papineau              0
René-Lévesque                  0
Saint-Antoine                  0
Saint-Urbain                   0
Totem_Laurier                  0
University                     0
Viger                          0
Max Temp (°C)                  0
Min Temp (°C)                  0
Mean Temp (°C)                 0
Heat Deg Days (°C)             0
Cool Deg Days (°C)             0
Total Rain (mm)                0
Total Snow (cm)                0
Total Precip (mm)              0
dtype: int64

<h3> model </h3>

In [344]:
y=df_merged[["Mean Temp (°C)"]]
df_merged.drop(columns=["Mean Temp (°C)"], inplace=True)
X=df_merged

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [345]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((246, 24), (62, 24), (246, 1), (62, 1))

In [346]:
def transform_train_val(X_train, X_test):
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    return X_train_scaled, X_test_scaled

In [348]:
X_train, X_test = transform_train_val(X_train, X_test)

In [349]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [350]:
y_train_pred = model.predict(X_train)
print(r2_score(y_train, y_train_pred))

1.0

In [351]:
y_pred_val = model.predict(X_test)
r2_score(y_test, y_pred_val)

1.0

<h3>model bikers sum </h3>

In [352]:
df_merged['Sum'] = df_merged[['Berri1', 'Boyer', 'Brébeuf', 'CSC (Côte Sainte-Catherine)', 'Maisonneuve_2', 'Maisonneuve_3', 'Notre-Dame', 'Parc', 'PierDup', 'Rachel / Hôtel de Ville', 'Rachel / Papineau', 'René-Lévesque', 'Saint-Antoine', 'Saint-Urbain', 'Totem_Laurier', 'University', 'Viger']].sum(axis=1)

In [353]:
df_merged.head()

,Berri1,Boyer,Brébeuf,CSC (Côte Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Rachel / Hôtel de Ville,...,University,Viger,Max Temp (°C),Min Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Snow (cm),Total Precip (mm),Sum
0,58,12,4,17,49,21,16,16,7,58,...,21,6,-3.0,-7.6,23.3,0.0,0.0,1.8,1.8,498
1,75,7,5,15,113,27,9,32,11,109,...,77,4,-3.4,-14.2,26.8,0.0,0.0,0.0,0.0,774
2,79,7,3,7,107,36,12,18,2,71,...,40,5,-8.5,-17.7,31.1,0.0,0.0,17.0,17.0,744
3,10,1,21,0,35,29,1,0,0,6,...,6,0,3.0,-8.6,20.8,0.0,26.8,0.4,27.2,148
4,42,0,2,0,90,21,1,1,6,0,...,56,10,-5.3,-17.9,29.6,0.0,0.0,0.0,0.0,344

In [354]:
df_bikers=df_merged.drop(['Berri1', 'Boyer', 'Brébeuf', 'CSC (Côte Sainte-Catherine)', 'Maisonneuve_2', 'Maisonneuve_3', 'Notre-Dame', 'Parc', 'PierDup', 'Rachel / Hôtel de Ville', 'Rachel / Papineau', 'René-Lévesque', 'Saint-Antoine', 'Saint-Urbain', 'Totem_Laurier', 'University', 'Viger'], axis=1)

In [355]:
df_bikers.head()

,Max Temp (°C),Min Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Snow (cm),Total Precip (mm),Sum
0,-3.0,-7.6,23.3,0.0,0.0,1.8,1.8,498
1,-3.4,-14.2,26.8,0.0,0.0,0.0,0.0,774
2,-8.5,-17.7,31.1,0.0,0.0,17.0,17.0,744
3,3.0,-8.6,20.8,0.0,26.8,0.4,27.2,148
4,-5.3,-17.9,29.6,0.0,0.0,0.0,0.0,344

In [357]:
y=df_merged[["Sum"]]
df_merged.drop(columns=["Sum"], inplace=True)
X=df_merged

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [358]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((246, 24), (62, 24), (246, 1), (62, 1))

In [359]:
def transform_train_val(X_train, X_test):
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    return X_train_scaled, X_test_scaled

In [360]:
X_train, X_test = transform_train_val(X_train, X_test)

In [367]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X_train)
X_poly

array([[1.        , 0.19779622, 0.17389891, ..., 0.        , 0.        ,
        0.05184561],
       [1.        , 0.22717998, 0.19827726, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.11168548, 0.12806761, ..., 0.        , 0.        ,
        0.30007876],
       ...,
       [1.        , 0.19181064, 0.15374614, ..., 0.        , 0.        ,
        0.05184561],
       [1.        , 0.67337777, 0.47131481, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.44674194, 0.42174549, ..., 0.        , 0.        ,
        0.        ]])

In [371]:
model = LinearRegression()
model.fit(X_poly, y_train)

LinearRegression()

In [372]:
y_train_pred=model.predict(X_poly)
print(r2_score(y_train, y_train_pred))

1.0

In [375]:
print(model.intercept_)

[373.31882381]